name: "Chromatic"

on: [push, pull_request]

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci

      - uses: chromaui/action@latest
        with:
          projectToken: chpt_d8c5c59f2c6fd6e
          exitZeroOnChanges: true
          debug: true
