name: "Chromatic"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v1.2.1
        with:
          bun-version: "latest"

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun build-lib

      - uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true
          debug: true
