name: "Chromatic"

on:
  pull_request:
    branches:
      - main

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm install
      - name: See secrets
        run: echo ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: "chpt_f1208002dbb3d00"
          zip: true
          onlyChanged: true
          buildScriptName: "build"
