# This workflow will run tests using node and then publish a package to GitHub Packages when a release is published
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - run: git config --global user.email "kpetunin@icloud.com"
      - run: git config --global user.name "git bot"

      - name: Install deps
        run: bun install --frozen-lockfile

      - name: Bump lib version
        run: |
          npm version --allow-same-version=true ${{ github.event.release.tag_name }}
          if ! git push origin HEAD:main; then
            echo "Ошибка при выполнении git push"
            exit 1
          fi

      - name: Build
        run: bun run build

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
